kind: pipeline
type: docker
name: {{ .input.pipeline_name }}


{{ with .input.trigger }}
trigger:
  {{ range .events }}
  event:
    - {{ . }}
  {{ end }}
  {{ range .branches }}
  branch:
    - {{ . }}
  {{ end }}
{{ end }}

steps:
   - name: build
     image: alpine
     commands:
        - whoami

   - name: hello world
     image: alpine
     commands:
     {{ range .input.hello_world_commands }}
     - {{ . }}
     {{ end }}

  {{ if .input.test_if.run }}
   - name: test if
     image: alpine
     commands:
       - echo "Running"
       {{ range .input.top_level }}
       - echo {{ .name }}
       {{ end }}
  {{ end }}

  {{ range .input.top_level }}
   - name: "{{ .name }} top_level"
     image: alpine
     commands:
       - echo "Hello {{ .greeting }}"
  {{ end }}
