kind: pipeline
type: docker
name: {{ .input.pipeline_name }}

trigger:
  event:
    - push
steps:
   - name: build
     image: alpine
     commands:
        - whoami

   - name: hello world
     image: alpine
     commands:
     {{ range .input.hello_world_commands }}
     - {{ . }}
     {{ end }}
