---
kind: pipeline
type: docker
name: params

trigger:
  event:
    - custom

steps:
  - name: show env
    image: alpine
    commands:
      - env

---
kind: pipeline
type: docker
name: on push

trigger:
  event:
    - push

steps:
  - name: Hello
    image: alpine
    commands:
      - echo "hello"

---
kind: template
load: example_template.yaml
data:
  trigger:
    events:
      - push
    branches:
      - testing
      - main
  pipeline_name: hello world
  hello_world_commands:
    - ls
    - whoami
  test_if:
    run: true

  top_level:
  - name: dev
    greeting: "hello world"
    image: python:3
  - name: foo
    greeting: FOOBAR
    image: alpine:latest
#---
