kind: pipeline
type: docker
name: {{ .input.pipeline_name }}


{{ with .input.trigger }}
trigger:
  {{ range .events }}
  event:
    - {{ . }}
  {{ end }}
  {{ range .branches }}
  branch:
    - {{ . }}
  {{ end }}
{{ end }}

steps:
   - name: build
     image: alpine
     commands:
        - whoami

   - name: hello world
     image: alpine
     commands:
     {{ range .input.hello_world_commands }}
     - {{ . }}
     {{ end }}
