kind: template
load: example_template.yaml
data:
  trigger:
    events:
      - push
    branches:
      - testing
      - main
  pipeline_name: hello world
  hello_world_commands:
    - ls
    - whoami
